### PR TITLE
Document nrdp API

### PR DESCRIPTION
**Pull request by mishan**
I discovered this hidden nrdp feature when perusing the code and thought it could use some documentation :)

### CODE REVIEW

**Comment by mishan** [comment]
@monnand

**Comment by monnand** [comment]
@mishan Aha, good catch! In fact, this feature was actually added for uniqush/uniqush-conn. I did not consider this feature would be there forever and was not sure if I should put it out there as a standard API. With that being said, do you think it's a useful feature?

**Comment by mishan** [comment]
@monnand It gives the number of delivery points (i.e. devices) between a subscriber and service, right? That's pretty useful for debugging. Also we've talked about wanting such an API before I found it in the code. We could easily look it up in Redis, but it's better to have uniqush-push be the source of authority.

**Comment by monnand** [comment]
@mishan Sounds reasonable. However, I'm not quite sure about the consistency model for this API. I need to check the code. But I am merging your PR anyway. Thanks!

**Comment by mishan** [comment]
Hm, yeah, it's actually part of something I've been wanting to look into. With 400-500 subscribe events / sec and 250-300 pushes / sec and 2 instances per host * 3 hosts, we get a small number of pushes fail with this message "Failed: Database Error Redis Error: Key does not exist" -- very small number, though. My only theory is that each instance has a cache and there could be inconsistency between the instances in that cache layer.

Since Redis is an in-memory data store and super fast, it makes sense for this API (or a similar one?) to just query Redis directly. But I wanted to understand the in memory model a bit more.

Do you hang out on any IRC networks ever? I would like to pick your brain sometime.

**Comment by monnand** [comment]
@mishan Definitely we should talk about this project. I do have an IRC channel for uniqush. But you can reach me through google hangout. My hangout account is same as my email address ( My github user name at gmail dot com)

I'm very interested in talking with you.

**Pull request merged**
